# Generated by Django 2.1.7 on 2019-06-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flightInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=10)),
                ('dep_time', models.TimeField()),
                ('dep_loc', models.CharField(max_length=31)),
                ('arr_time', models.TimeField()),
                ('arr_loc', models.CharField(max_length=31)),
                ('flight_schedule', models.CharField(max_length=20)),
                ('norm_price', models.IntegerField()),
                ('dur_time', models.TimeField()),
            ],
        ),
    ]
